# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ğŸ˜ï¸](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color 
error_symbol = "[#](bold red)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"


[aws]
disabled = true

[rust]
disabled = true

[git_branch]
#format = "on [$branch]($style) "

[dotnet]
disabled = true


